#!/usr/bin/env bash

shopt -s nullglob
shopt -s dotglob

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

seconds_since_epoch=$(date +%s)

for f in "${dir}/files/"*; do
  filename="$(basename "${f}")"
  installed_file="${HOME}/${filename}"

  if [ -f "${installed_file}" ]; then
    # Only back up file if not equivalent to install file
    if [ "$(stat -f "%Y" "${installed_file}")" != "${f}" ]; then
      backup="${installed_file}.${seconds_since_epoch}.bak"
      i=1
      while [ -f "${backup}" ]; do
        backup="${installed_file}.${seconds_since_epoch}.${i}.bak"
        ((i++))
      done
      mv "${installed_file}" "${backup}" && echo "Backed up ${installed_file} (to ${backup})"
    fi
  fi
done
