#!/usr/bin/env bash

shopt -s nullglob
shopt -s dotglob

self="${BASH_SOURCE[0]}"
dir="$(cd "$(dirname "${self}")" && pwd)"
script="$(basename "${self}")"
hooks="${dir}/hooks"

backup="${dir}/backup"
source "${backup}"

pre="${hooks}/pre-${script}"
if [ -f "${pre}" ]; then
  source "${pre}"
fi

for f in "${dir}/files/"*; do
  filename="$(basename "${f}")"
  installed_file="${HOME}/${filename}"

  ln -sf "${f}" "${installed_file}" && echo "Installed ${installed_file}"
done

post="${hooks}/post-${script}"
if [ -f "${post}" ]; then
  source "${post}"
fi
