#!/usr/bin/env bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

backup="${dir}/backup"
source "${backup}"

pre="${dir}/pre-install"
if [ -f "${pre}" ]; then
  source "${pre}"
fi

files="$(cat "${dir}/files")"
for f in ${files}; do
  installed_file="${HOME}/${f}"
  ln -sf "${dir}/${f}" "${installed_file}" && echo "Installed ${installed_file}"
done

post="${dir}/post-install"
if [ -f "${post}" ]; then
  source "${post}"
fi
