#!/usr/bin/env bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

backup="${dir}/backup"
source "${backup}"

pre="${dir}/pre-install"
if [ -f "${pre}" ]; then
  source "${pre}"
fi

files="$(cat "${dir}/files")"
for f in ${files}; do
  ln -sf "${dir}/${f}" "${HOME}/${f}" && echo "Installed ${HOME}/${f}"
done

post="${dir}/post-install"
if [ -f "${post}" ]; then
  source "${post}"
fi
