#!/usr/bin/env bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

shopt -s nullglob

for f in "${dir}/files/"*; do
  filename="$(basename "${f}")"
  installed_file="${HOME}/${filename}"

  for backup_file in "${installed_file}".*.bak; do
    rm "${backup_file}" && echo "Removed ${backup_file}"
  done
done

shopt -u nullglob
