#!/usr/bin/env bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

files="$(cat "${dir}/files")"
for f in ${files}; do
  installed_file="${HOME}/${f}"
  if [ -e "${installed_file}" ] || [ -h "${installed_file}" ]; then
    rm "${installed_file}" && echo "Removed ${installed_file}"
  fi
done

restore="${dir}/restore"
source "${restore}"
