#!/usr/bin/env bash

shopt -s nullglob
shopt -s dotglob

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
hooks="${dir}/hooks"

pre="${hooks}/pre-uninstall"
if [ -f "${pre}" ]; then
  source "${pre}"
fi

for f in "${dir}/files/"*; do
  filename="$(basename "${f}")"
  installed_file="${HOME}/${filename}"

  if [ -e "${installed_file}" ] || [ -h "${installed_file}" ]; then
    rm "${installed_file}" && echo "Removed ${installed_file}"
  fi
done

post="${hooks}/post-uninstall"
if [ -f "${post}" ]; then
  source "${post}"
fi

restore="${dir}/restore"
source "${restore}"
