#!/usr/bin/env bash

shopt -s nullglob
shopt -s dotglob

self="${BASH_SOURCE[0]}"
dir="$(cd "$(dirname "${self}")" && pwd)"
script="$(basename "${self}")"
source "${dir}/utils"

source_hook pre "${script}" "${dir}"

for f in "${dir}/files/"*; do
  filename="$(basename "${f}")"
  installed_file="${HOME}/${filename}"

  if [ -e "${installed_file}" ] || [ -h "${installed_file}" ]; then
    rm "${installed_file}" && echo "Removed ${installed_file}"
  fi
done

source_hook post "${script}" "${dir}"

source "${dir}/restore"
