#!/usr/bin/env bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
hooks="${dir}/hooks"

pre="${hooks}/pre-update"
if [ -f "${pre}" ]; then
  source "${pre}"
fi

pushd "${dir}" > /dev/null
rev_before_pull=$(git rev-parse HEAD)
git pull
rev_after_pull=$(git rev-parse HEAD)
popd > /dev/null

if [ "${rev_before_pull}" != "${rev_after_pull}" ]; then
  post="${hooks}/post-update"
  if [ -f "${post}" ]; then
    source "${post}"
  fi
fi
