#!/usr/bin/env bash

self="${BASH_SOURCE[0]}"
dir="$(cd "$(dirname "${self}")" && pwd)"
script="$(basename "${self}")"
source "${dir}/utils"

source_hook pre "${script}" "${dir}"

pushd "${dir}" > /dev/null
if [ -d .git ]; then
  rev_before_pull=$(git rev-parse HEAD)
  git pull
  rev_after_pull=$(git rev-parse HEAD)
fi
popd > /dev/null

if [ "${rev_before_pull}" != "${rev_after_pull}" ]; then
  source_hook post "${script}" "${dir}"
fi
