#!/usr/bin/env bash

self="${BASH_SOURCE[0]}"
dir="$(cd "$(dirname "${self}")" && pwd)"
script="$(basename "${self}")"
hooks="${dir}/hooks"

pre="${hooks}/pre-${script}"
if [ -f "${pre}" ]; then
  source "${pre}"
fi

pushd "${dir}" > /dev/null
rev_before_pull=$(git rev-parse HEAD)
git pull
rev_after_pull=$(git rev-parse HEAD)
popd > /dev/null

if [ "${rev_before_pull}" != "${rev_after_pull}" ]; then
  post="${hooks}/post-${script}"
  if [ -f "${post}" ]; then
    source "${post}"
  fi
fi
